server/code/serveradmin/luffy/models/__init__.py
#coding=utf-8

from u import AdminUser, Servers, Mongos, UserLog, SyncTables, FilterPlayer
from u import RenRate
from mygamebase import MongoFive, DEFAULT_HOST, DEFAULT_PORT, MongoDrive
from xls2mongo import xls2mongo,code2mongo, mac2count, get_pay_log, create_ws
from aes import new_aes_encrypt
from daycount import ComplexCount, NewComplexCount
from daycount import CCount, NewCCountToday, NewCCount, ccount_all
from daycount import NewComplexCountToday, get_r, c2dict
from daycount import RetentionCount2, RetentionCount7, RetentionCount15
from gm import Gm

server/code/serveradmin/luffy/models/user.py
#coding=utf-8

server/code/serveradmin/luffy/forms/__init__.py
#coding=utf-8

from u import LoginForm,RegForm,FindPwdForm,PasswordForm

server/code/serveradmin/luffy/forms/app_service.py
# -*- coding:utf-8 -*-


from flask import url_for
from flask_wtf import Form
from wtforms import TextAreaField, HiddenField, BooleanField,RadioField,\
    TextField, ValidationError, DateField,IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired, URL
from webapi import SNS_MAP


class AppConfigForm(Form):
    """
    苹果软件配置
    """
    platform = SelectField(u'选择平台', choices=[(k, v) for k, v in SNS_MAP.iteritems() if k > 0], coerce=int)
    download_url = TextField(u'下载地址')
    name = TextField(u'游戏名称')
    icon = TextField(u'图标')
    bundleid = TextField(u'软件包的bundle-id')
    web_url = TextField(u'web下载地址',
            validators=[DataRequired(u'web下载地址不能为空'), URL(message=u"地址格式不正确")])
    mobile_url = TextField(u'手机端下载地址')

server/code/serveradmin/luffy/forms/gamebase.py
#coding=utf-8
from flask.ext.wtf import Form, TextAreaField, BooleanField, RadioField,TextField, \
        SubmitField, PasswordField,ValidationError, DateField, required
        
from luffy.resp import BaseAjaxForm
        
        
class RoleLevelForm(BaseAjaxForm):
    level = TextField(u'等级',validators=[required(message=u'请输入等级')])
    exp = TextField(u'经验', validators=[required(message=u'请输入经验')])
    siteExp = TextField(u'打坐经验', validators=[required(message=u'打坐经难')])
    
    def validate_level(self, field):
        if field.data == '':
            raise ValidationError, u"等级不能为空。"

server/code/serveradmin/luffy/__init__.py
#coding=utf-8
from os.path import join
from bson.objectid import ObjectId
from flask import Flask, g, session, request, flash, redirect, jsonify, url_for,render_template
from werkzeug.wsgi import DispatcherMiddleware
# from flask.ext.principal import Principal, RoleNeed, UserNeed, identity_loaded
from tprincipal import Principal, RoleNeed, UserNeed, identity_loaded
from time import time
from models import AdminUser, Servers
from models.u import mdb
from extensions import db
from define import GAMEBASE_LOCAL, GAMEBASE_SERVER, GAME_LOG_LOCAL, GAME_LOG_SERVER
from define import GAME_BASEUSER_TEST_SERVER, GAMEBASE_TEST,  GAME_BASEUSER_LOCAL
from define import TEST_ROLE_LIST, GAME_BASEUSER_SERVER, GAME_TD_G
# from adminconfig import AdminConfig, Admin91Config, ZLConfig, ZLTestConfig
from helps import build_url
from define import NUM_UNIX_A_DAY
import config as game_config
from corelib import log
import views
import pymongo
from luffy.models import MongoDrive
from luffy.client_app import application as clientsvr


DEFAULT_MODULES = (
    (views.frontend,""),
    (views.user,"/user"),
    (views.admin,"/admin"),
    (views.other,"/other")
)

def create_app(config=None, modules=None):
    if modules is None:
        modules = DEFAULT_MODULES

    app = Flask(__name__)

    # 安装配置文件
#    app.config.from_pyfile(config)
    app.config.from_object(game_config.BaseConfig())
    # 配置一些扩展组件
    configure_extensions(app)
    # 配置权限功能
    configure_identity(app)
    # 错误处理模块
    configure_errorhandlers(app)
    # 用户信息加载模块
    configure_before_handlers(app)
    # 模板的一些过滤功能
    configure_template_filters(app)
    # 上传的一些功能配置
    #configure_uploads(app, (photos,))
    # 注册所有站点模块
    configure_modules(app, modules)

    application = DispatcherMiddleware(app, {
    '/service':     clientsvr
    })
    return application

_conns = {}
def get_conn(host):
    print '*****', host
    if host in _conns:
        return _conns[host]
    else:
        _conns[host] = pymongo.Connection(host=host[0], port=int(host[1]))
        return _conns[host]

_mongo_conns = {}
def get_mongo_conn(host, port):
    if host in _mongo_conns:
        return _mongo_conns[host]
    else:
        mongo = MongoDrive()
        _mongo_conns[host] = mongo.connect(host, int(port))
        return _mongo_conns[host]

def configure_identity(app):
    """ 对用户权限进行配置 """
    Principal(app)
    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        KEY_USERNAME    = 'username'
        KEY_PASSWORD    = 'password'
        GRPC_PORT       = '8001'
        MONGO_USERNAME_PASSWORD  = 'mongodb://%s:%s@%s'
        MONGO_IP                 = 'mongodb://%s'
        DB_RES_DEFAULT  = 'td_res'
        DB_USER_DEFAULT = 'td'
        DB_LOG_DEFAULT  = 'td_log'
        DB_COUNT        = 'td_count'
        RES_PATH_DEFAULT = '/data/webroot/www/game/config/zl/ver/'

        g.servers_group = Servers.query.distinct(Servers.db_res)
        g.user = AdminUser.query.from_identity(identity)
        if g.user is not None:
            if not g.user.server_group:
                g.servers = Servers.query.filter().sort((Servers.name,-1)).all()
            else:
                g.servers = Servers.query.filter(Servers.db_res==g.user.server_group).sort((Servers.name,-1)).all()
            mongo_host = None
            for s in g.servers:
                if s.mongo_id == g.user.server:
                    mongo_host = s
            if not mongo_host:
                if g.user.role == 400:
                    mongo_host = g.servers[0]
                else:
                    for s in g.servers:
                        try:
                            if g.user.right[14] == 1:
                                if s.t == 3:
                                    mongo_host = s
                            if g.user.right[13] == 0:
                                if s.t != 3:
                                    mongo_host = s
                        except:
                            continue

            mongo_host = mongo_host or g.servers[-1]


            if mongo_host:
                ip = mongo_host.ip
                port = mongo_host.port
                gport = mongo_host.gport
                if hasattr(mongo_host, KEY_USERNAME) and hasattr(mongo_host, KEY_PASSWORD):
                    if mongo_host.username and mongo_host.password:
                        ip = MONGO_USERNAME_PASSWORD % (mongo_host.username, mongo_host.password, ip)
                else:
                    ip = MONGO_IP % ip
                db_res  = mongo_host.db_res
                db_user = mongo_host.db_user
                db_log  = mongo_host.db_log
                db_count  = mongo_host.st
                res_path = mongo_host.res
                current_server = mongo_host
                g.user.server = ObjectId(mongo_host.mongo_id)
                session['g_user_server'] = mongo_host.mongo_id
            else:
                base_config = game_config.BaseConfig()
                ip          = base_config.MONGOALCHEMY_SERVER
                port        = base_config.MONGOALCHEMY_PORT
                cuser       = base_config.MONGOALCHEMY_USER
                cpassword   = base_config.MONGOALCHEMY_PASSWORD
                gport       = ':'.join([ip, GRPC_PORT])
                if cuser is None and cpassword is None:
                    ip = MONGO_IP % ip
                else:
                    ip = MONGO_USERNAME_PASSWORD % (cuser, cpassword, ip)
                db_res  = DB_RES_DEFAULT
                db_user = DB_USER_DEFAULT
                db_log  = DB_LOG_DEFAULT
                db_count = DB_COUNT
                res_path = RES_PATH_DEFAULT
                current_server = None
#            ip = '172.16.40.2'
            g.conns = get_conn((ip, port))
            g.mongo_drive = get_mongo_conn(ip, port)
            g.current_server = current_server
            g.GAMEBASE      = db_res
            g.GAME_BASEUSER = db_user
            g.GAME_LOG      = db_log
            g.GAME_COUNT    = db_count
            g.mongo_host    = ip
            g.res_path      = res_path
        #更新用户的最后登录时间
        if g.user is not None  and time() - g.user.lastlogin > NUM_UNIX_A_DAY:
                g.user.new_login()

def configure_extensions(app):
    # 初始化一些扩展
    db.init_app(app)
    mdb.init_app(app)
    db_config = app.config.get('MONGODB_SETTINGS')

    db_config = dict([(k.lower(), v) for k, v in db_config.items() if v])
    db_name = db_config.pop('db')
    mdb.register_connection(db_name, db_name, **db_config)
    dbs = Servers.query.distinct(Servers.db_res)
    for res_db in dbs:
        s = Servers.query.filter(Servers.db_res == res_db, Servers.ip!='127.0.0.1').first()
        if s:
            host = s.ip
            db_config.update({'host': host, 'username': s.username, 'password': s.password})
            mdb.register_connection(res_db, res_db, **db_config)

def configure_modules(app, modules):
    for module, url_prefix in modules:
        app.register_blueprint(module, url_prefix = url_prefix)

def configure_before_handlers(app):
    @app.before_request
    def authenticate():
        if not hasattr(g,'user'):
            g.user = None

def configure_template_filters(app):
    @app.template_filter()
    def url(action,filename,_external = False):
        return build_url(app,action,filename,_external)

    @app.template_filter()
    def string(val):
        return str(val)

    @app.template_filter()
    def rd(val, val2):
        return '%.20f' % (val/val2)

    @app.template_filter()
    def division(val=None, val2=None):
        if not val:
            val = 0
        if not val2 or val2 == 0:
            return 0
        return '%.2f' % (val/float(val2))

    @app.template_filter()
    def percent(val=None, val2=None):
        if not val:
            val = 0
        if not val2 or val2 == 0:
            return 0
        return '%.2f' % (val/float(val2)*100)

    @app.template_filter()
    def setRen(val, date):
        if date == '2013-06-20':
            return round(val*1.4, 2)
        return val

    @app.template_filter()
    def show_cout_day(alist, stype):
        ret = []
        for val in alist:
            if stype == 'year':
                ret.append(val.split('-')[0])
            if stype == 'month':
                ret.append(val)
            if stype == 'day':
                tmp = val.split('-')
                ret.append('-'.join([tmp[1], tmp[2]]))
            if stype == 'hour':
                ret.append('-'.join([val.split(' ')[0].split('-')[2], val.split(' ')[1]]))
        return ret


    @app.template_filter()
    def format_date(date,s='%Y-%m-%d %H:%M'):
        from datetime import datetime
        try:
            date = datetime.fromtimestamp(date)
            return date.strftime(s)
        except:
            return ''

    @app.template_filter()
    def short(val, num=33):
        if len(val) > num:
            return val[:num]
        return val

    @app.template_filter()
    def cout_day(alist, stype):
        ret = []
        for val in alist:
            val = format_date(val, s='%Y-%m-%d %H')
            if stype == 'year':
                ret.append(val.split('-')[0])
            if stype == 'month':
                ret.append(val)
            if stype == 'day':
                tmp = val.split('-')
                ret.append('-'.join([tmp[1], tmp[2]]))
            if stype == 'hour':
                ret.append('-'.join([val.split(' ')[0].split('-')[2], val.split(' ')[1]]))
        return ret

    @app.template_filter()
    def integer(val):
        if val:
            return int(val)
        return ''

    @app.template_filter()
    def float2(val, dec=2):
        return round(float(val), dec)

    @app.template_filter()
    def format_date_list(alist, s='%Y-%m-%d %H:%M'):
        try:
            return [format_date(item, s) for item in alist]
        except:
            return []

    @app.template_filter()
    def encode(val):

server/code/serveradmin/luffy/views/__init__.py
#coding=utf-8

from .frontend import frontend
from .admin import admin
from .user import user, FiveMethods
from .other import other

server/code/serveradmin/luffy/views/frontend.py
#coding=utf-8
from flask import Blueprint, render_template, request, current_app,\
    redirect, g,jsonify,Session,session,send_from_directory, url_for

from luffy.resp import resp  
from bson.objectid import ObjectId 
from luffy.forms import LoginForm,RegForm,FindPwdForm,PasswordForm 
import os
frontend = Blueprint('frontend', __name__,static_folder='static')


@frontend.route("/", methods = ("GET", "POST"))
@resp()
def index():

    return redirect(url_for('frontend.login'))

@frontend.route("/link/", methods = ("GET", "POST"))
@resp()
def link():

    return {}


@frontend.route("/login/", methods = ("GET", "POST"))
@resp()
def login():
    '''
    登录系统
    '''    
    return LoginForm(next = request.args.get('next',None))

@frontend.route("/reg/", methods = ("GET", "POST"))
@resp()
def reg():
    '''
    注册用户，注意无需激活
    '''
    return RegForm()


@frontend.route("/forgot/", methods = ("GET", "POST"))
@resp()
def forgot():
    '''
    忘记密码
    '''
    return FindPwdForm()

@frontend.route("/password/<string:key>/<string:id>/", methods = ("GET", "POST"))
@resp()
def password(key,id):
    '''
    找回密码邮件后重设密码
    '''
    return PasswordForm(uid = id,token = key)

 

server/code/serveradmin/luffy/views/other.py
#coding=utf-8

from flask import Blueprint, request, current_app, redirect, g,session,url_for
from luffy.permissions import other as o
from luffy.resp import resp
from luffy.models import FilterPlayer, RenRate
from bson.objectid import ObjectId

other = Blueprint('other', __name__,static_folder='static')

@other.route("/", methods=("GET", "POST"))
@o.require(401)
@resp()
def index():
    return {'SIDEBAR':'other'}

@other.route('/server/filter/', methods=('GET', 'POST'))
@o.require(401)
@resp()
def server_filter():
    """  """
    page = int(request.args.get('page', '1'))
    filter_player = FilterPlayer.query.paginate(page, per_page=50)
    count = FilterPlayer.query.count()
    tmp = count%50 
    page_count = count/50
    if tmp != 0:
        page_count += 1
    return {'SIDEBAR':'other', "ret":filter_player, "page":page, "page_count":page_count}

@other.route('/server/filter/order/', methods=('GET', 'POST'))
@o.require(401)
@resp(ret='json')
def server_filter_order():
    """  """
    STR_TYPE, STR_NAMES, STR_T = 'opType', 'names', 't'
    opType = request.form.get(STR_TYPE)
    names = request.form.get(STR_NAMES)
    t = request.form.get(STR_T)
    if t:
        t=int(t)
    if opType == 'new':
        names = names.split("\n")
        for item in names:
            if item != '':
                filter_player = FilterPlayer()
                filter_player.n = item
                filter_player.t = t
                filter_player.save()
    elif opType == 'edit':
        sid = request.form.get("id")
        player = FilterPlayer.query.get_or_404(ObjectId(sid))
        player.n = names
        player.t = t 
        player.save()
    elif opType == 'del':
        print 'opType', opType
        sid = request.form.get("id")
        player = FilterPlayer.query.get_or_404(ObjectId(sid))
        player.remove()
    return {'SIDEBAR':'other', 'success':1}


@other.route('/rate/order/', methods=('GET', 'POST'))
@o.require(401)
@resp(ret='json')
def rate_order():
    """  """
    STR_T, STR_R, STR_S = 't', 'r', 's'
    t = float(request.form.get(STR_T))
    r = float(request.form.get(STR_R))
    s = request.form.get(STR_S)
    if RenRate.change_r(t,r,s):
        return {'success':1}
    return {'success':0}

server/code/serveradmin/luffy/templates/other/index.html
{% extends "other/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}

{% endblock %}
{%- block main -%}
    <div class="span10">      
    </div><!--/row-->

</div><!--/.fluid-container-->

<script type="text/javascript">
    $(document).ready(function(){
        $("#submit").click(function(){
            var names = $("#names").val();
            var t = $("#t").val();
            var url = "{{ url_for('other.server_filter_order') }}";
            $.post(url,{
                names:names,t:t, opType:"new"
            },function(data){
                if(data['success'] == 0){
                    alert("添加角色等级失败");
                }else{
                    location.reload() 
                }
            });
        });
        $("#edit_submit").click(function(){
            var id = $("#edit_id").val();
            var names = $("#edit_names").val();
            var t = $("#edit_t").val();
            var url = "{{ url_for('other.server_filter_order') }}";
            $.post(url,{
                id:id,names:names,t:t, opType:"edit"
            },function(data){
                if(data['success'] == 0){
                    alert("修改失败");
                }else{
                    location.reload() 
                }
            });
        });
        
    });
</script>
{%- endblock -%}

server/code/serveradmin/luffy/templates/other/layout.html
{%- extends "base_layout.html" -%}
{%- block css -%}
<link rel="stylesheet" href="{{ 'frontend.static'|url('bootstrap/css/bootstrap.min.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ 'frontend.static'|url('bootstrap/css/bootstrap-responsive.min.css') }}" type="text/css" />  
{%- endblock -%} 
{%- block bootjs-%}
<script type="text/javascript" src="{{ 'frontend.static'|url('bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ 'frontend.static'|url('js/efun.js') }}"></script>
<script type="text/javascript" src="{{ 'frontend.static'|url('js/My97DatePicker/WdatePicker.js') }}"></script>
<script type="text/javascript" src="{{ 'frontend.static'|url('js/HighchartsJS/highcharts.js') }}"></script>
<script type="text/javascript" src="{{ 'frontend.static'|url('js/HighchartsJS/modules/exporting.js') }}"></script>
{% block subjs %}{% endblock%}
{%- endblock -%}
{%- block content -%}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            {% set test_user = ['qe@efun.com'] %}
            <a class="brand" href="#">
                {% if g.current_server %}
                {{ g.current_server.name }}
                {% else %}
                指点真龙
                {% endif %}
            </a>
            <div class="nav-collapse collapse">

            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          {% if not user_index%}
          <div class="well sidebar-nav">
                <div class="accordion" id="accordion2">
                  <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseAdminStatus">
                        管理员功能
                      </a>
                    </div>
                    <div id="collapseAdminStatus" class="{% if SIDEBAR == 'other' %}accordion-body in{% else %}accordion-body collapse{% endif %}">
                      <div class="accordion-inner">
                        <ul>
                              <li><a href="{{ url_for('other.server_filter') }}">名单</a></li>
                              <hr />
                         </ul>
                      </div>
                    </div>
                  </div>
              </div>
          </div><!--/.well -->
          {% endif %}
        </div><!--/span-->
    {%- block main -%}{%- endblock -%}
{%- endblock -%}

server/code/serveradmin/luffy/templates/other/server_filter.html
{% extends "other/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}

{% endblock %}
{%- block main -%}
        <div class="span10">
            
            <div class="well form-inline">
                名单:
                <textarea id="names"></textarea>
                类型:
                <select class="span2" id="t">
                    <option value="1">pid</option>
                    <option value="2">uid</option>
                </select>
                <button type="button" class="btn" id='submit'>增加服务器</button>
                
            </div>
            <div class="well form-inline hidefive" id="disfive">
                编辑：<br />
                id:
                <input type="text" class="input-big" id="edit_id" readonly="readonly">
                名单:
                <textarea id="edit_names"></textarea>
                类型:
                <select class="span2" id="edit_t">
                    <option value="1">pid</option>
                    <option value="2">uid</option>
                </select>
                <button type="button" class="btn" id='edit_submit'>提交</button>
                <button type="button" class="btn" id='edit_cancel' onclick="$(this).parent().attr('class','well form-inline hidefive')">取消</button>
            </div>
            {{ paginate(page_count,url_for('other.server_filter'),current_page=page) }}
            <table class="table table-bordered">
                <tr>
                    <td>名单</td>
                    <td>类型</td>
                    <td>操作</td>
                </tr>
                {%- for r in ret.items -%}
                <tr>
                    <td><p id='{{ r.mongo_id }}_names'>{{ r.n }}</p></td>
                    <td><p id='{{ r.mongo_id }}_t'>{{ r.t }}</p></td>
                    <td>
                        <button type="button" class="btn" onclick="GAME.load.filter(this, '{{ r.mongo_id }}')" stype="del" href="/other/server/filter/order/">删除</button>
                        <button type="button" class="btn" onclick="GAME.load.filter(this, '{{ r.mongo_id }}')" stype="edit" href="/other/server/filter/order/">编辑</button>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div><!--/row-->

</div><!--/.fluid-container-->

<script type="text/javascript">
    $(document).ready(function(){
        $("#submit").click(function(){
            var names = $("#names").val();
            var t = $("#t").val();
            var url = "{{ url_for('other.server_filter_order') }}";
            $.post(url,{
                names:names,t:t, opType:"new"
            },function(data){
                if(data['success'] == 0){
                    alert("添加角色等级失败");
                }else{
                    location.reload() 
                }
            });
        });
        $("#edit_submit").click(function(){
            var id = $("#edit_id").val();
            var names = $("#edit_names").val();
            var t = $("#edit_t").val();
            var url = "{{ url_for('other.server_filter_order') }}";
            $.post(url,{
                id:id,names:names,t:t, opType:"edit"
            },function(data){
                if(data['success'] == 0){
                    alert("修改失败");
                }else{
                    location.reload() 
                }
            });
        });
        
    });
</script>
{%- endblock -%}

server/code/serveradmin/luffy/templates/other/setting.html
{% extends "other/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}

{% endblock %}
{%- block main -%}
        <div class="span10">
            
            <div class="well form-inline">
                key:
                <input type="text" class="input-big" id="key">
                value:
                <input type="text" class="input-big" id="value">
                <button type="button" class="btn" id='submit'>增加</button>
                
            </div>
            <div class="well form-inline hidefive" id="disfive">
                编辑：<br />
                id:
                <input type="text" class="input-big" id="edit_id" readonly="readonly">
                key:
                <input type="text" class="input-big" id="edit_key">
                value:
                <input type="text" class="input-big" id="edit_value">
                <button type="button" class="btn" id='edit_submit'>提交</button>
                <button type="button" class="btn" id='edit_cancel' onclick="$(this).parent().attr('class','well form-inline hidefive')">取消</button>
            </div>
            <table class="table table-bordered">
                <tr>
                    <td>key</td>
                    <td>value</td>
                    <td>操作</td>
                </tr>
                {%- for r in ret -%}
                <tr>
                    <td><p id='{{ r.mongo_id }}_key'>{{ r.key }}</p></td>
                    <td><p id='{{ r.mongo_id }}_value'>{{ r.value }}</p></td>
                    <td>
                        <button type="button" class="btn" onclick="GAME.load.other_setting(this, '{{ r.mongo_id }}')" stype="del" href="/other/setting/order/">删除</button>
                        <button type="button" class="btn" onclick="GAME.load.other_setting(this, '{{ r.mongo_id }}')" stype="edit" href="/other/setting/order/">编辑</button>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div><!--/row-->

</div><!--/.fluid-container-->

<script type="text/javascript">
    $(document).ready(function(){
        $("#submit").click(function(){
            var key = $("#key").val();
            var val = $("#value").val();
            var url = "{{ url_for('other.setting_order') }}";
            $.post(url,{
                key:key, val:val, opType:"new"
            },function(data){
                if(data['success'] == 0){
                    alert("添加角色等级失败");
                }else{
                    location.reload() 
                }
            });
        });
        $("#edit_submit").click(function(){
            var id = $("#edit_id").val();
            var key = $("#edit_key").val();
            var val = $("#edit_value").val();
            var url = "{{ url_for('other.setting_order') }}";
            $.post(url,{
                key:key, val:val, id:id, opType:"edit"
            },function(data){
                if(data['success'] == 0){
                    alert("修改失败");
                }else{
                    location.reload() 
                }
            });
        });
        
    });
</script>
{%- endblock -%}