server/code/serveradmin/luffy/models/__init__.py
#coding=utf-8

from u import AdminUser, Servers, Mongos, UserLog, SyncTables, FilterPlayer
from u import RenRate
from mygamebase import MongoFive, DEFAULT_HOST, DEFAULT_PORT, MongoDrive
from xls2mongo import xls2mongo,code2mongo, mac2count, get_pay_log, create_ws
from aes import new_aes_encrypt
from daycount import ComplexCount, NewComplexCount
from daycount import CCount, NewCCountToday, NewCCount, ccount_all
from daycount import NewComplexCountToday, get_r, c2dict
from daycount import RetentionCount2, RetentionCount7, RetentionCount15
from gm import Gm

server/code/serveradmin/luffy/models/user.py
#coding=utf-8

server/code/serveradmin/luffy/forms/__init__.py
#coding=utf-8

from u import LoginForm,RegForm,FindPwdForm,PasswordForm

server/code/serveradmin/luffy/forms/app_service.py
# -*- coding:utf-8 -*-


from flask import url_for
from flask_wtf import Form
from wtforms import TextAreaField, HiddenField, BooleanField,RadioField,\
    TextField, ValidationError, DateField,IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired, URL
from webapi import SNS_MAP


class AppConfigForm(Form):
    """
    苹果软件配置
    """
    platform = SelectField(u'选择平台', choices=[(k, v) for k, v in SNS_MAP.iteritems() if k > 0], coerce=int)
    download_url = TextField(u'下载地址')
    name = TextField(u'游戏名称')
    icon = TextField(u'图标')
    bundleid = TextField(u'软件包的bundle-id')
    web_url = TextField(u'web下载地址',
            validators=[DataRequired(u'web下载地址不能为空'), URL(message=u"地址格式不正确")])
    mobile_url = TextField(u'手机端下载地址')

server/code/serveradmin/luffy/forms/gamebase.py
#coding=utf-8
from flask.ext.wtf import Form, TextAreaField, BooleanField, RadioField,TextField, \
        SubmitField, PasswordField,ValidationError, DateField, required
        
from luffy.resp import BaseAjaxForm
        
        
class RoleLevelForm(BaseAjaxForm):
    level = TextField(u'等级',validators=[required(message=u'请输入等级')])
    exp = TextField(u'经验', validators=[required(message=u'请输入经验')])
    siteExp = TextField(u'打坐经验', validators=[required(message=u'打坐经难')])
    
    def validate_level(self, field):
        if field.data == '':
            raise ValidationError, u"等级不能为空。"

server/code/serveradmin/luffy/views/__init__.py
#coding=utf-8

from .frontend import frontend
from .admin import admin
from .user import user, FiveMethods
from .other import other

server/code/serveradmin/luffy/views/frontend.py
#coding=utf-8
from flask import Blueprint, render_template, request, current_app,\
    redirect, g,jsonify,Session,session,send_from_directory, url_for

from luffy.resp import resp  
from bson.objectid import ObjectId 
from luffy.forms import LoginForm,RegForm,FindPwdForm,PasswordForm 
import os
frontend = Blueprint('frontend', __name__,static_folder='static')


@frontend.route("/", methods = ("GET", "POST"))
@resp()
def index():

    return redirect(url_for('frontend.login'))

@frontend.route("/link/", methods = ("GET", "POST"))
@resp()
def link():

    return {}


@frontend.route("/login/", methods = ("GET", "POST"))
@resp()
def login():
    '''
    登录系统
    '''    
    return LoginForm(next = request.args.get('next',None))

@frontend.route("/reg/", methods = ("GET", "POST"))
@resp()
def reg():
    '''
    注册用户，注意无需激活
    '''
    return RegForm()


@frontend.route("/forgot/", methods = ("GET", "POST"))
@resp()
def forgot():
    '''
    忘记密码
    '''
    return FindPwdForm()

@frontend.route("/password/<string:key>/<string:id>/", methods = ("GET", "POST"))
@resp()
def password(key,id):
    '''
    找回密码邮件后重设密码
    '''
    return PasswordForm(uid = id,token = key)

 

server/code/serveradmin/luffy/views/other.py
#coding=utf-8

from flask import Blueprint, request, current_app, redirect, g,session,url_for
from luffy.permissions import other as o
from luffy.resp import resp
from luffy.models import FilterPlayer, RenRate
from bson.objectid import ObjectId

other = Blueprint('other', __name__,static_folder='static')

@other.route("/", methods=("GET", "POST"))
@o.require(401)
@resp()
def index():
    return {'SIDEBAR':'other'}

@other.route('/server/filter/', methods=('GET', 'POST'))
@o.require(401)
@resp()
def server_filter():
    """  """
    page = int(request.args.get('page', '1'))
    filter_player = FilterPlayer.query.paginate(page, per_page=50)
    count = FilterPlayer.query.count()
    tmp = count%50 
    page_count = count/50
    if tmp != 0:
        page_count += 1
    return {'SIDEBAR':'other', "ret":filter_player, "page":page, "page_count":page_count}

@other.route('/server/filter/order/', methods=('GET', 'POST'))
@o.require(401)
@resp(ret='json')
def server_filter_order():
    """  """
    STR_TYPE, STR_NAMES, STR_T = 'opType', 'names', 't'
    opType = request.form.get(STR_TYPE)
    names = request.form.get(STR_NAMES)
    t = request.form.get(STR_T)
    if t:
        t=int(t)
    if opType == 'new':
        names = names.split("\n")
        for item in names:
            if item != '':
                filter_player = FilterPlayer()
                filter_player.n = item
                filter_player.t = t
                filter_player.save()
    elif opType == 'edit':
        sid = request.form.get("id")
        player = FilterPlayer.query.get_or_404(ObjectId(sid))
        player.n = names
        player.t = t 
        player.save()
    elif opType == 'del':
        print 'opType', opType
        sid = request.form.get("id")
        player = FilterPlayer.query.get_or_404(ObjectId(sid))
        player.remove()
    return {'SIDEBAR':'other', 'success':1}


@other.route('/rate/order/', methods=('GET', 'POST'))
@o.require(401)
@resp(ret='json')
def rate_order():
    """  """
    STR_T, STR_R, STR_S = 't', 'r', 's'
    t = float(request.form.get(STR_T))
    r = float(request.form.get(STR_R))
    s = request.form.get(STR_S)
    if RenRate.change_r(t,r,s):
        return {'success':1}
    return {'success':0}

server/code/serveradmin/luffy/views/user.py
#coding=utf-8

from bson.objectid import ObjectId
from luffy.define import STRING_NONE

import traceback
from flask import Blueprint, request, current_app, redirect, g,session,url_for, flash
import luffy.define as EXT
from luffy.models import MongoFive, Servers, Mongos, UserLog,DEFAULT_PORT, MongoDrive
from luffy.models import SyncTables, FilterPlayer, RenRate
from luffy.resp import resp
from bson.objectid import ObjectId
from luffy.permissions import moderator
from tprincipal import identity_changed,  AnonymousIdentity
from luffy.helps import print_traceback, range_list
from luffy.helps import format_date, get_format, xlsupload
import time, os, datetime, re, json
from bson.code import Code
from corelib import log
from webapi  import  SNS_MAP
import config as game_config
from game.base.common import get_days
from luffy.helps import strptime, time_to_hour, grpc_get_proxy
from luffy.forms.cp import QaccoutForm
from luffy.forms.cp import CoinQueryForm
from luffy.forms.cp import MailForm
from luffy.forms.cp import LangForm
from luffy.models.u import LangConf
from luffy.forms.app_service import AppConfigForm
from corelib import log
from corelib.tools import http_post_ex

user = Blueprint('user', __name__,static_folder='static')

is_check = ic_retention2 = ic_retention7 = ic_retention15 = True

@user.route("/", methods = ("GET", "POST"))
@moderator.require(401)
@resp()
def index():
    return {  }

@user.route("/show/", methods = ("GET", "POST"))
@moderator.require(401)
@resp(template="user/index.html")
def index_show():
    user_index = 'user_index'
    return { 'user_index':user_index }

@user.route('/client/servers/', methods=('GET','POST'))
@moderator.require(401)
@resp()
def client_servers():
    """ 客户端服务器列表 """
    mongo = MongoFive(g.GAMEBASE, EXT.COLL_SERVER, host=g.mongo_host)
    ret = mongo.all()
    return { 'SIDEBAR':'ADMIN', 'ret':ret }

@user.route('/client/servers/save/', methods=('GET','POST'))
@moderator.require(401)
@resp(ret='json')
def client_servers_save():
    """ 客户端服务器列表数据保存 """
    STR_DATA, STR_HOST, STR_PORT, STR_SID, STR_APP   = 'data', 'host', 'port', 'sid', 'app'
    STR_NAME, STR_STATUS, STR_CONDITION     = 'name', 'status', 'condition'
    id      = request.form.get(EXT.KEY_ID)
    host    = request.form.get(STR_HOST)
    port    = request.form.get(STR_PORT)
    name    = request.form.get(STR_NAME)
    status  = request.form.get(STR_STATUS)
    sid     = request.form.get(STR_SID)
    app     = request.form.get(STR_APP)
    try:
        mongo = MongoFive(g.GAMEBASE, EXT.COLL_SERVER, host=g.mongo_host)
        insert_val = {
            EXT.KEY_MONGO_ID    : int(id),
            STR_HOST            : host,
            STR_PORT            : int(port),
            STR_NAME            : name,
            STR_STATUS          : int(status),
            STR_SID             : int(sid),
            STR_APP             : app
        }
        args = { STR_CONDITION:{EXT.KEY_MONGO_ID:int(id)}, STR_DATA:insert_val}
        mongo.update(args)
        return { 'success':'1', 'id':id }
    except:
        print_traceback()
        return { 'success':'0' }

@user.route('/client/servers/delete/', methods=('GET','POST'))
@moderator.require(401)
@resp(ret='json')
def client_servers_delete():
    """ 客户端服务器列表单数据删除 """
    try:
        id = int(request.args.get('id'))
        mongo = MongoFive(g.GAMEBASE, EXT.COLL_SERVER, host=g.mongo_host)
        mongo.delete(id)
        return { 'success':'1' }
    except:
        print_traceback()
        return { 'success':'0' }

@user.route('/client/servers/data/', methods=('GET','POST'))
@moderator.require(401)
@resp(ret='json')
def client_servers_data():
    """ 客户端服务器列表单数据获取 """
    try:
        id = int(request.args.get('id'))
        mongo = MongoFive(g.GAMEBASE, EXT.COLL_SERVER, host=g.mongo_host)
        ret = mongo.get_by_id(int(id))
        return { 'success':'1', 'ret':ret}
    except:
        print_traceback()
        return { 'success':'0'}
#=============================================================

@user.route('/database/backup/', methods=('GET', 'POST'))
@moderator.require(401)
@resp()
def database_backup():
    """ 数据库备份页面 """
#    backup_path = current_app.config.get('MONGO_BACKUP_PATH')
    backup_path = game_config.MONGO_BACKUP_PATH
    ret = None
    if os.path.isdir(backup_path):
        ret = os.listdir(backup_path)
        ret = [item for item in ret if not item.startswith('.')]
    return { 'SIDEBAR':'ADMIN', 'ret':ret }

@user.route('/database/backup/operation/', methods=('GET', 'POST'))
@moderator.require(401)
@resp(ret='json')
def database_backup_operation():
    """ 数据库备份操作部份 """
#    backup_path = current_app.config.get('MONGO_BACKUP_PATH')
    backup_path = game_config.MONGO_BACKUP_PATH
    opType = request.args.get('opType')
    server = Servers.query.get(g.user.server)
    if opType == 'dump':
        tmp_path = ''.join([backup_path, str(datetime.date.fromtimestamp(time.time())), '/'])
        dump_order = ['mongodump', '-h', server.ip, '-o', tmp_path]
        if hasattr(server, 'username') and server.username:
            dump_order.append('-u')
            dump_order.append(server.username)
        if hasattr(server, 'password') and server.password:
            dump_order.append('-p')
            dump_order.append(server.password)
        os.system(' '.join(dump_order))
    if opType != 'dump':
        backup_date = request.args.get('backup_date')
        path = ''.join([backup_path, backup_date])
    if opType == 'del':
        import shutil
        shutil.rmtree(path)
    if opType == 'restore':
        restore_order = ['mongorestore', '-h', server.ip, '-directoryperdb', path]
        os.system(' '.join(restore_order))
    return { 'success':1 }


@user.route('/database/restore/', methods=('GET', 'POST'))
@moderator.require(401)
@resp()
def database_restore():
    """ 数据库同步页面 """
    ret = Mongos.query.sort().all()
    tables = SyncTables.query.all()
    return { 'SIDEBAR':'ADMIN', 'ret':ret, 'tables':tables }

@user.route('/database/restore/tables/', methods=('GET', 'POST'))
@moderator.require(401)
@resp()
def database_restore_tables():
    """ 数据库同步表 """
    tables = SyncTables.query.all()
    return { 'SIDEBAR':'ADMIN', 'tables':tables }

@user.route('/database/restore/tables/save/', methods=('GET', 'POST'))
@moderator.require(401)
@resp(ret='json')
def database_restore_tables_save():
    """ 数据库同步表保存 """
    names = request.form.get('names', None)
    title = request.form.get('title', None)
    remark = request.form.get('remark', None)
    oid = request.form.get('id', None)
    opType = request.form.get('opType')
    if opType == 'add':
        tables = SyncTables()
    if opType == 'edit':
        tables = SyncTables.query.get_or_404(ObjectId(oid))
    if opType == 'add' or opType == 'edit':
        tables.names = names
        tables.title = title
        tables.remark = remark
        tables.save()
    if opType == 'del':
        tables = SyncTables.query.get_or_404(ObjectId(oid))
        tables.remove()
    return { 'SIDEBAR':'ADMIN', 'success':1 }

@user.route('/database/restore/operation/<string:opType>/', methods=('GET', 'POST'))
@moderator.require(401)
@resp(ret='json')
def database_restore_operation(opType):
    """ 数据库同步配置操作 """
    mongos = Mongos()
    if opType == 'add' or opType == 'edit':
        ip              = request.form.get('ip', None)
        port            = request.form.get('port', None)
        username        = request.form.get('username', None)
        password        = request.form.get('password', None)
        database        = request.form.get('database', None)
        tables          = request.form.get('tables', None)
        remark          = request.form.get('remark', None)
        st          = request.form.get('st', 'zl')
        isDrop          = int(request.form.get('isDrop', '1'))
        localdatabase   = request.form.get('localdatabase', None)
        t = int(request.form.get('t', 1))
        id = request.form.get('id', '')
        if id:
            mongos = Mongos.query.get_or_404(ObjectId(id))
        else:
            mongos = Mongos()
            if not ip:
                return {'success':0}
        if ip:
            mongos.ip = ip
        if port:
            mongos.port = int(port)
        mongos.username = username
        mongos.password = password
        if tables:
            mongos.tables = ObjectId(tables)
        if database:
            mongos.database = database
        if remark:
            mongos.remark = remark
        if localdatabase:
            mongos.localdatabase = localdatabase
        mongos.t = t
        mongos.st = st
        mongos.is_drop = isDrop
        mongos.save()
        return {'success':1}
    elif opType == 'del':
        id = request.form.get('id', '')
        try:
            id = ObjectId(id)
        except:
            raise 404
        mongos = Mongos.query.get_or_404(id)
        mongos.remove()
        return {'success':1}
    return { 'success':0 }

#@user.route('/database/server/restore/', methods=('GET', 'POST'))
#@moderator.require(401)
#@resp(ret='json')
#def database_server_restore():
#    """ 数据库同步操作 """
#    import subprocess
#    success = 1
#    info    = ''
#    opType = request.args.get('opType')
#    mid = request.args.get('mid')
#    isDrop = int(request.args.get('isDrop'))
#    print "isDrop************", isDrop
#    #获取source源地址信息， target目标信息
#    if opType == 'push':
#        source = Servers.query.get(g.user.server)
#        target = Mongos.query.get_or_404(ObjectId(mid))
#        database = target.database
#        collections = target.table_names.split('\n')
#        local_database = target.localdatabase
#        fileDatabase = local_database
#    if opType == 'pull':
#        source = Mongos.query.get_or_404(ObjectId(mid))
#        target = Servers.query.get(g.user.server)
#        local_database = source.database
#        collections = source.table_names.split('\n')
#        database = source.localdatabase

server/code/serveradmin/luffy/templates/user/common_search_result.html
{% extends "user/layout.html"%}
{%- block main -%}

		<div class="span9">
			<div id="search-container">
			</div>
			<div id="search-data">
		{%if data%}
				<table class="table table-striped table-bordered table-condensed">
					{%- for r in data -%}

					{%if loop.first%}
					<tr>
						{%for k in form.order_keys()%} 
						<td>{{form[k].label}}</td>
						{%endfor%}
					</tr>
					{%endif%}

					<tr>
						{%for k in form.order_keys()%} 
						<td>{{r[k]}}</td>
						{%endfor%}
					</tr>	

					{% endfor %}  
				</table>
		{%endif%}
		</div>
			
		</div>
	</div><!--/row-->

</div><!--/.fluid-container-->
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/customer_account.html
{% extends "user/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}

{% endblock %}
{%- block main -%}
{% if g.user.role >= 300 or g.user.right[4] == 1 %}
<div class="span10">
    <!-- type:1=efun, 2=云顶 -->
    <div class="well form-inline">
        id:
        <input type="text" class="input-small" id="id">
        email：
        <input type="text" class="input-big" id="email">
        password：
        <input type="text" class="input-big" id="password">
        type:
        <input type="text" class="input-big" id="t">
        <button type="button" class="btn" id='submit'>增加服务器</button>
    </div>
    <div class="well form-inline hidefive" id="disfive">
        编辑：<br />
        id:
        <input type="text" class="input-big" id="edit_id" readonly="readonly">
        email：
        <input type="text" class="input-big" id="edit_email">
        password：
        <input type="text" class="input-big" id="edit_password">
        type:
        <input type="text" class="input-big" id="edit_t">
        <button type="button" class="btn" id='edit_submit'>提交</button>
        <button type="button" class="btn" id='edit_cancel' onclick="$(this).parent().attr('class','well form-inline hidefive')">取消</button>
    </div>
    <table class="table table-bordered">
        <tr>
            <td>id</td>
            <td>email</td>
            <td>password</td>
            <td>type</td>
            <td>操作</td>
        </tr>
        {%- for r in ret -%}
        <tr>
            <td>{{ r['_id'] }}</td>
            <td>{{ r['email'] }}</td>
            <td>{{ r['password'] }}</td>
            <td>{{ r['t'] }}</td>
            <td>
                {% if g.user.role >= 300 or g.user.right[0] == 1 %}
                <button type="button" class="btn" id="delete" val="{{ r._id }}" onclick="GAME.load.href_click(this)" stype="del" href="{{ url_for('user.customer_account_delete') }}">删除</button>
                <button type="button" class="btn" id="edit" val="{{ r._id }}" onclick="GAME.load.edit_click(this, 'customer_account')" stype="edit" href="{{ url_for('user.customer_account_data') }}">编辑</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}

    </table>
</div>
{% endif %}
</div><!--/row-->

</div><!--/.fluid-container-->

<script type="text/javascript">
    $(document).ready(function(){
        $("#submit").click(function(){
            var id = $("#id").val();
            var email = $("#email").val();
            var password = $("#password").val();
            var t = $("#t").val();
            var url = "{{ url_for('user.customer_account_save') }}";
            $.post(url,{
                id:id, email:email, password:password, t:t
            },function(data){
                if(data['success'] == 0){
                    alert("添加角色等级失败");
                }else{
                    location.reload()
                }
            });
        });
        $("#edit_submit").click(function(){
            var id = $("#edit_id").val();
            var email = $("#edit_email").val();
            var password = $("#edit_password").val();
            var t = $("#edit_t").val();
            var url = "{{ url_for('user.customer_account_save') }}";
            $.post(url,{
                id:id, email:email, password:password, t:t
            },function(data){
                if(data['success'] == 0){
                    alert("修改失败");
                }else{
                    location.reload()
                }
            });
        });
    });
</script>
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/database_restore_tables.html
{% extends "user/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}
<script xmlns="http://www.w3.org/1999/html">
    function backup(obj, opType){
        if(confirm("确定执行吗?")){
            var url = $(obj).attr('href');
            var mid = $(obj).attr('mid');
            var img_html = "{{ 'frontend.static'|url('images/loading.gif') }}";
            $('#show_loading').append('<img src="'+img_html+'" />');
            $.get(url,{opType:opType, mid:mid},function(d){
                $('#show_loading').html(d['info']);
            });
        }

    };
</script>
{% endblock %}
{%- block main -%}
{% if g.user.role >= 300  or g.user.right[4] == 1 %}
<div class="span10">
    <div id="show_loading"></div>
    <div class="well form-inline">
        标识:
        <input class="input-big" id="title"></input>
        表名:
        <textarea type="text" class="input-big" id="names"></textarea>
        备注:
        <textarea type="text" class="input-big" id="remark"></textarea>
        <button type="button" class="btn" id='submit'>保存</button>
    </div>
    <div class="well form-inline hidefive" id="disfive">
        <input class="input-big" id="edit_id" readonly></input>
        标识:
        <input class="input-big" id="edit_title"></input>
        所有表名:
        <textarea type="text" class="input-big" id="edit_names"></textarea>
        备注:
        <textarea type="text" class="input-big" id="edit_remark"></textarea>
        <button type="button" class="btn" id='edit_submit'>保存</button>
        <button type="button" class="btn" id='edit_cancel' onclick="$(this).parent().attr('class','well form-inline hidefive')">取消</button>
    </div>
    <table class="table table-bordered">
        <tr>
            <td>标识</td>
            <td>所有表名</td>
            <td>备注</td>
        </tr>
        {%- for r in tables -%}
        <tr>

            <td><p id='{{ r.mongo_id }}_title'>{{ r.title }}</p></td>
            <td><p id='{{ r.mongo_id }}_names'>{{ r.names }}</p></td>
            <td><p id='{{ r.mongo_id }}_remark'>{{ r.remark }}</p></td>
            <td>
                {% if g.user.role >= 300 or g.user.right[0] == 1 %}
                <button type="button" class="btn" onclick="GAME.load.database_restore_tables_save(this, '{{ r.mongo_id }}')" stype="del" href="/user/database/restore/tables/save/">删除</button>
                <button type="button" class="btn" onclick="GAME.load.database_restore_tables_save(this, '{{ r.mongo_id }}')" stype="edit" href="/user/database/restore/tables/save/">编辑</button>
                <br />
                {% endif %}
            </td>
        </tr>
        {% endfor %}

    </table>
</div>
{% endif %}
</div><!--/row-->

</div><!--/.fluid-container-->

<script type="text/javascript">
    $(document).ready(function(){
        $("#submit").click(function(){
            var title = $("#title").val();
            var names = $("#names").val();
            var remark = $("#remark").val();
            var url = "{{ url_for('user.database_restore_tables_save') }}";
            $.post(url,{
                names:names, title:title, remark:remark, opType:"add"
            },function(data){
                if(data['success'] == 0){
                    alert("添加角色等级失败");
                }else{
                    location.reload()
                }
            });
        });
        $("#edit_submit").click(function(){
            var id = $("#edit_id").val();
            var title = $("#edit_title").val();
            var names = $("#edit_names").val();
            var remark = $("#edit_remark").val();
            var url = "{{ url_for('user.database_restore_tables_save') }}";
            $.post(url,{
                names:names, id:id, title:title, remark:remark, opType:"edit"
            },function(data){
                if(data['success'] == 0){
                    alert("修改失败");
                }else{
                    location.reload()
                }
            });
        });
    });
</script>
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/log_info.html
{% extends "user/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}
<script type="text/javascript" src="{{ 'frontend.static'|url('js/sorttable.js') }}"></script>
{% endblock%}
{%- block main -%}
{% if g.user.role >= 300 or g.user.right[10] == 1 %}
<div class="span10">
    <br />
    玩家信息日志:
    开始时间：<input type="text" class="input-small" id="start_time"  onClick="WdatePicker()" value="{{ start_time }}">
    结束时间<input type="text" class="input-small" id="end_time"  onClick="WdatePicker()" value="{{ end_time }}">
    类型：<input type="text" class="input-small" id="t" value="{{ t }}">
    <button type="button" class="btn" href="{{ url_for('user.log_info') }}" onclick="GAME.load.log_rpc(this)">查询</button>
    {{ paginate(page_count,url_for('user.log_info'),current_page=page) }}
    <table class="table table-bordered sortable" id="unique_id">
        <tr>
            <td>ID</td>
            <td>玩家id</td>
            <td>类型</td>
            <td>使用时间</td>
            <td>附加信息</td>
        </tr>
        {% for v in ret %}
        <tr>
            <td>{{ v['_id'] }}</td>
            <td>{{ v['p'] }}</td>
            <td>{{ v['t'] }}</td>
            <td>{{ v['ct']|format_date }}</td>
            <td>{{ v['d'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
</div><!--/row-->

</div><!--/.fluid-container-->
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/log_user.html
{% extends "user/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}
<script type="text/javascript" src="{{ 'frontend.static'|url('js/sorttable.js') }}"></script>
{% endblock%}
{%- block main -%}
{% if g.user.role >= 300 or g.user.right[2] == 1 %}
		<div class="span10">

			<br />
			开始时间：<input type="text" class="input-small" id="start_time"  onClick="WdatePicker()" value="{{ start_time }}"> 
			结束时间<input type="text" class="input-small" id="end_time"  onClick="WdatePicker()" value="{{ end_time }}">
            类型：<input type="text" class="input-small" id="t" value="{{ t }}">
			<button type="button" class="btn" href="{{ url_for('user.log_user') }}" onclick="GAME.load.log_rpc(this)">查询</button>
			<table class="table table-bordered sortable" id="unique_id">
				<tr>

					<td>用户</td>

                    <td>类型</td>
                    <td>详细</td>
                    <td>时间</td>
				</tr>
				{% for k in ret %}
				<tr>
					<td>{{ k.u }}</td>
                    <td>{{ k.ty }}-{%if k.ty==1%}用户登录{%elif k.ty==2%}GM指令{%endif%}</td>
                    <td>{{ k.i }}</td>
                    <td>{{ k.t|format_date }}</td>
                </tr>
				{% endfor %}
			</table>
		</div>
		{% endif %}
 	</div><!--/row-->

</div><!--/.fluid-container-->
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/mac_compare.html
{% extends "user/layout.html"%}
{% from "base_macros.html" import paginate %}
{% block subjs %}
<script type="text/javascript">
</script>
{% endblock%}
{%- block main -%}
{% if g.user.role >=300 or g.user.right[9] == 1 %}
        <div class="span10">
            <form action="" method="POST" enctype="multipart/form-data"  class="well form-inline">
                选择xls/xlsx文件：  <input type="file" name="xlsfile">
                <input type="submit" value="提交">
            </form>
            
        </div>
        {{ count }}
        {% endif %}
    </div><!--/row-->
</div><!--/.fluid-container-->
{%- endblock -%}

server/code/serveradmin/luffy/templates/user/udid.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h1>{{ count }}</h1>
{% for r in ret %}
{{ r }}<br/>
{% endfor %}
</body>
</html>